---
title: "Untitled"
format: html
---


```{r}
library(slingshot)
library(Seurat)
library(dplyr)
library(ggplot2)
library(scran)
library(scater)
library(igraph)
library(tidyr)
library(viridis)
```

```{r}
catcar <- readRDS("car_only_basic_annotation.rds")
```

### extract individual elements of data for slingshot input
```{r}
dimred <- catcar@reductions$umap@cell.embeddings
clustering <- catcar$basic_clusters
counts <- catcar[["RNA"]]$counts
```

```{r}
set.seed(61)
sce <- SingleCellExperiment(
  assays = list(counts = counts)
)

reducedDim(sce, "UMAP") <- dimred
colData(sce)$cluster <- clustering

sce <- slingshot(
  sce,
  clusterLabels = "cluster",
  reducedDim = "UMAP",
  start.clus = "c6"
)
```

### summary of results
```{r}
SlingshotDataSet(sce)
```

### save object to not have to run again
```{r}
saveRDS(sce, file = "slingshot_output/catcar_slingshot_object.rds")
```

```{r}
palette <- ggsci::pal_d3("category20")(20)

# Create a color lookup table
cluster_cols <- setNames(
  palette[seq_along(levels(clustering))],
  levels(clustering)
)

# Assign a color to each cell based on its cluster
cell_cols <- cluster_cols[as.character(clustering)]
```

### extracting MST and nodes to plot manually using ggplot
```{r}
mst <- slingMST(sce)

nodes <- data.frame(
  cluster = V(mst)$name,
  do.call(rbind, vertex_attr(mst, "coordinates"))
)

colnames(nodes)[2:3] <- c("UMAP_1", "UMAP_2")

nodes
```

```{r}
edge_list <- as.data.frame(get.edgelist(mst))

colnames(edge_list) <- c("from", "to")
```

```{r}
edges <- edge_list %>%
  left_join(nodes, by = c("from" = "cluster")) %>%
  rename(x = UMAP_1, y = UMAP_2) %>%
  left_join(nodes, by = c("to" = "cluster")) %>%
  rename(xend = UMAP_1, yend = UMAP_2)

edges
```

```{r}
cell_df <- data.frame(
  UMAP_1 = reducedDim(sce, "UMAP")[,1],
  UMAP_2 = reducedDim(sce, "UMAP")[,2],
  cluster = sce$cluster
)

p <- ggplot(cell_df, aes(UMAP_1, UMAP_2)) +
  geom_point(aes(colour = cluster), size = 0.3) +
  geom_segment(
    data = edges,
    aes(
      x = x,
      y = y,
      xend = xend,
      yend = yend
    ),
    inherit.aes = FALSE,
    linewidth = 1.2,
    colour = "black"
  ) +
    geom_point(
    data = nodes,
    aes(UMAP_1, UMAP_2),
    inherit.aes = FALSE,
    size = 4,
    colour = "black"
  ) +
  scale_colour_manual(values = cluster_cols) +
  theme_classic()
p
ggsave(plot=p, filename = "pseudotime_MST_umap.png", dpi = 300, height = 6, width = 8)
```

```{r}
curves <- slingCurves(sce)
curves
```

```{r}
curve_dfs <- lapply(seq_along(curves), function(i) {

  crv <- curves[[i]]

  data.frame(
    UMAP_1 = crv$s[,1],
    UMAP_2 = crv$s[,2],
    lineage = paste0("Lineage_", i),
    order = seq_len(nrow(crv$s))
  )
})

curve_df <- do.call(rbind, curve_dfs)
curve_df$lineage <- gsub("_", "", curve_df$lineage)
```

```{r}
slingLineages(lineages)
```

```{r}
lin <- slingLineages(lineages)

terminal_cluster <- sapply(lin, tail, 1)

lineage_cols <- cluster_cols[terminal_cluster]
lineage_cols <- scales::alpha(lineage_cols, 0.7)

# CRITICAL FIX:
names(lineage_cols) <- names(lin)
```

```{r}
p <- ggplot(cell_df, aes(UMAP_1, UMAP_2)) +

  # --- cells (cluster colour scale 1)
  geom_point(
    aes(colour = cluster),
    size = 0.3, alpha = 0.1
  ) +
  scale_colour_manual(values = cluster_cols) +

  ggnewscale::new_scale_colour() +

  # --- lineages (second independent colour scale)
  geom_path(
    data = curve_df,
    aes(
      UMAP_1,
      UMAP_2,
      group = lineage,
      colour = lineage
    ),
    linewidth = 1.7,
    arrow = arrow(type = "closed", length = unit(0.15, "inches"))
  ) +
  scale_colour_manual(values = lineage_cols) +

  theme_classic()
p
ggsave(plot=p, filename = "pseuodtime_lineages_umap.png", dpi = 300, height = 6, width = 8)
```

### add lineage info to cell_df to be able to plot on umap
```{r}
pt <- slingPseudotime(sce)
cell_df$pt_L1 <- pt[, "Lineage1"]
cell_df$pt_L2 <- pt[, "Lineage2"]
cell_df$pt_L3 <- pt[, "Lineage3"]
cell_df$pt_L4 <- pt[, "Lineage4"]
cell_df$pt_L5 <- pt[, "Lineage5"]
```
```{r}
pt_df <- as.data.frame(pt)
pt_df$cell <- rownames(pt_df)

pt_long <- pivot_longer(
  pt_df,
  cols = starts_with("Lineage"),
  names_to = "lineage",
  values_to = "pseudotime"
)
pt_long <- merge(pt_long, cell_df, by.x = "cell", by.y = "row.names")
```

```{r}
p <- ggplot(pt_long, aes(UMAP_1, UMAP_2, color = pseudotime)) +
  geom_point(size = 0.3) +
  facet_wrap(~ lineage, ncol=1) +
  scale_color_viridis(option = "rocket", direction = -1) +
  theme_void()+
  theme(strip.text=element_text(size=14, colour = "black", face = "bold"))
p
ggsave(plot = p, filename= "catcar_pseudotime_gradient_umaps.png", dpi = 300, height = 6, width = 2)
```


